### ISSUE TITLE
Doesn't work with arrow functions

### ISSUE THREAD

**Issue by cinan** [brendenpalmer/eslint-plugin-disable-features#3]
I don't get error on `async () => {}`

**Comment by rwjblue** [comment]
Thanks for reporting! We need to add `ArrowFunctionExpression` to [this object](https://github.com/brendenpalmer/eslint-plugin-disable-features/blob/master/lib/rules/disable-async-await.js#L26).  

Mind sending in a PR?

**Comment by cinan** [comment]
i'll see what i can do (never written eslint plugin) 👍
